version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "tools"
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "ci"
