services:
  acceptance:
    image: mcr.microsoft.com/devcontainers/go:2-1.26-trixie
    volumes:
      - ..:/workspaces/terraform-provider-rustfs
    working_dir: /workspaces/terraform-provider-rustfs
    command: bash -c "\
      ls && \
      cp .terraformrc ~/.terraformrc && \
      go mod tidy && \
      go build -buildvcs=false && \
      TF_ACC=1 go test ./provider/  || true && \
      TF_ACC=1 go test ./provider/  && \
      echo something
      "
    depends_on:
      rustfs:
        condition: service_started

  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.99
    ports:
      - "8000:9000"
      - "8001:9001"
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_CONSOLE_ENABLE: true
